language: java

services:
  - cassandra

before_install:
 - chmod +x gradlew

before_script:
  # give some more time for Cassandra to finish startup and actually test it
  - sleep 10
  - sudo service cassandra status

script:
  - ./gradlew clean test --debug --tests mertz.security.oauth2.provider.token.store.cassandra.CassandraTokenStoreTests
