language: java

services:
  - cassandra

before_install:
  - chmod +x gradlew

install:
  # skip ./gradlew assemble since it fails on :bootRepackage task with 'Unable to find main class' error which is expected.
  - true

before_script:
  # give some more time for Cassandra to finish startup and actually test it
  - sleep 10
  - sudo service cassandra status

script:
  - ./gradlew clean test --debug --tests mertz.security.oauth2.provider.token.store.cassandra.CassandraTokenStoreTests
  
#after_success:
#  - ./gradlew clean test --tests mertz.security.oauth2.provider.token.store.cassandra.CassandraTokenStoreTests jacocoTestReport coveralls:report
